name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        echo NOOP set -e
        printf '%s\n' 'ALJUNK: go' 1>&2
        /usr/bin/env 1>&2
        printf '%s\n' 'ALJUNK: A'   1>&2
        echo home decl is ${HOME@A} 1>&2
        printf '%s\n' 'ALJUNK: a'   1>&2
        echo $(pwd)                 1>&2
        printf '%s\n' 'ALJUNK: b'   1>&2
        ls -la                      1>&2
        printf '%s\n' 'ALJUNK: c'   1>&2
        echo maybe tty: $(tty)      1>&2
        printf '%s\n' 'ALJUNK: d'   1>&2
        set -x
        grep intel_pt /proc/cpuinfo 1>&2 || true
        echo FOO                    1>&2
        cat /etc/apt/sources.list   1>&2 || true
        echo FOOO                   1>&2
        find /etc/apt -ls           1>&2 || true
        echo FOOOO                  1>&2
        grep -R -e 'ddeb' -e 'dbgsym' /etc/apt 1>&2 || true
        echo FOOOOO                            1>&2
        echo "deb http://ddebs.ubuntu.com $(lsb_release -cs) main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ddebs.list || true
        echo FOOOOOO                 1>&2
        cat /etc/apt/sources.list.d/ddebs.list 1>&2 || true
        echo FOOOOOOO                1>&2
        grep -R -e 'ALJUNK-second' -e 'ddeb' -e 'dbgsym' /etc/apt  1>&2 || true
        sudo apt-get --assume-yes install -V ubuntu-dbgsym-keyring 1>&2 || true
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622 1>&2
        sudo apt-get update         1>&2 || true
        echo NOOP sudo apt-get --assume-yes install -V apt-file 1>&2 || true
        echo NOOP sudo apt-file update                          1>&2 || true
        echo FOOOOOOOO
        echo NOOP apt-cache search ruby | grep '^ruby' | sort || true
        sudo apt-get --assume-yes install -V debian-goodies || true
        sudo apt-get --assume-yes install -V gdb            || true
        echo NOOP sudo apt-get --assume-yes --allow-downgrades install -V ruby2.5=2.5.1-1ubuntu1 libruby2.5=2.5.1-1ubuntu1 || true
        sudo apt-get --assume-yes --allow-downgrades install -V ruby2.5=2.5.1-1ubuntu1 libruby2.5=2.5.1-1ubuntu1 ruby2.5-dbgsym=2.5.1-1ubuntu1 libruby2.5-dbgsym=2.5.1-1ubuntu1 libgmp10-dbgsym || true
        sudo apt-get --assume-yes install -V ruby2.6        || true
        echo FOOOOOOOOO
        apt-cache policy ruby2.5           1>&2 || true
        apt-cache policy ruby2.5-dbgsym    1>&2 || true
        apt-cache policy libruby2.5        1>&2 || true
        apt-cache policy libruby2.5-dbgsym 1>&2 || true
        echo NOOP sudo apt-get --assume-yes --allow-downgrades install -V libgmp10-dbgsym libruby2.5-dbgsym=2.5.1-1ubuntu1 ruby2.5-dbgsym=2.5.1-1ubuntu1 || true
        echo FOOOOOOOOOO
        find-dbgsym-packages /usr/bin/ruby2.6 || true
        echo FOOOOOOOOOOO
        find-dbgsym-packages /usr/bin/ruby2.5 || true
        set +x
        printf '%s\n' 'ALJUNK: B'   1>&2
        echo home ech: $HOME        1>&2
        echo home exp: ~            1>&2
        printf '%s\n' 'ALJUNK: C'   1>&2
        getent passwd runner        1>&2
        printf '%s\n' 'ALJUNK: D'   1>&2
        getent passwd               1>&2
        printf '%s\n' 'ALJUNK: E'   1>&2
        set                         1>&2
        printf '%s\n' 'ALJUNK: F'   1>&2
        ruby -e 'print "ruby dir home: #{Dir.home}\n";' 1>&2
        ruby -e 'print "ruby dir pwd:  #{Dir.pwd}\n";'  1>&2
        ruby -e 'print Dir.respond_to?(:home)   ? "yep1\n" : "nope1\n";' 1>&2
        ruby -e 'print File.readable?(Dir.home) ? "yep2\n" : "nope2\n";' 1>&2
        printf '%s\n' 'ALJUNK: G'   1>&2
        set -x
        cat - <<EOS > scmd
        #!/bin/bash -
        printf 'start of scmd\n' 1>&2
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec --keep-file-descriptors ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)' 
        EOS
        chmod 0755 scmd
        script -e -f -c './scmd' output.aljunk || printf 'AL.DEBUG: estat of scmd: %s\n' "$?" 1>&2 && true || true
        printf 'after: start of scmd output:\n' 1>&2
        echo NOOP cat output.aljunk                       1>&2
        printf 'after: end of scmd output:\n'   1>&2
        set +x
        printf '%s\n' 'ALJUNK: H'   1>&2
        set -x
        set +x
        printf '%s\n' 'ALJUNK: I'   1>&2
        printf '%s\n' 'ALJUNK: end' 1>&2
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec --keep-file-descriptors ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
