name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        echo NOOP set -e
        printf '%s\n' 'ALJUNK: go' 1>&2
        /usr/bin/env 1>&2
        printf '%s\n' 'ALJUNK: A'   1>&2
        echo home decl is ${HOME@A} 1>&2
        printf '%s\n' 'ALJUNK: a'   1>&2
        echo $(pwd)                 1>&2
        printf '%s\n' 'ALJUNK: b'   1>&2
        ls -la                      1>&2
        printf '%s\n' 'ALJUNK: c'   1>&2
        echo maybe tty: $(tty)      1>&2
        printf '%s\n' 'ALJUNK: d'   1>&2
        set -x
        grep intel_pt /proc/cpuinfo 1>&2 || true
        cat /proc/cpuinfo           1>&2 || true
        echo FOO                    1>&2
        #
        : BEFORE APT MUCKAGE
        apt-cache policy ruby2.5    1>&2 || true        
        #
        #
        cat /etc/apt/sources.list   1>&2 || true
        echo FOOO                   1>&2
        sudo sed -i -e 's,^# \(deb-src http://azure.archive.ubuntu.com/ubuntu/ bionic main restricted\)$,\1,' /etc/apt/sources.list || true
        echo NOOP sudo sed -i -e 's,^# \(deb-src http://azure.archive.ubuntu.com/ubuntu/ bionic-updates main restricted\)$,\1,' /etc/apt/sources.list || true
        echo NOOP sudo sed -i -e 's,^# \(deb-src http://azure.archive.ubuntu.com/ubuntu/ bionic universe\)$,\1,' /etc/apt/sources.list || true
        echo NOOP sudo sed -i -e 's,^# \(deb-src http://azure.archive.ubuntu.com/ubuntu/ bionic-updates universe\)$,\1,' /etc/apt/sources.list || true
        echo NOOP sudo sed -i -e 's,^# \(\)$,\1,' /etc/apt/sources.list || true
        echo NOOP sudo sed -i -e 's,^# \(\)$,\1,' /etc/apt/sources.list || true
        echo NOOP sudo sed -i -e 's,^# \(\)$,\1,' /etc/apt/sources.list || true
        echo NOOP sudo sed -i -e 's,^# \(\)$,\1,' /etc/apt/sources.list || true
        echo NOOP sudo sed -i -e 's,^# \(\)$,\1,' /etc/apt/sources.list || true
        : ALJUNK check contents of modified .../apt/sources.list
        cat /etc/apt/sources.list   1>&2 || true
        find /etc/apt -ls           1>&2 || true
        echo FOOOO                  1>&2
        grep -R -e 'ddeb' -e 'dbgsym' /etc/apt 1>&2 || true
        echo FOOOOO                            1>&2
        echo "deb http://ddebs.ubuntu.com $(lsb_release -cs) main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ddebs.list || true
        echo FOOOOOO                 1>&2
        cat /etc/apt/sources.list.d/ddebs.list 1>&2 || true
        echo FOOOOOOO                1>&2
        grep -R -e 'ALJUNK-second' -e 'ddeb' -e 'dbgsym' /etc/apt  1>&2 || true
        sudo apt-get --assume-yes install -V ubuntu-dbgsym-keyring 1>&2 || true
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622 1>&2
        sudo apt-get update         1>&2 || true
        echo NOOP sudo apt-get --assume-yes install -V apt-file 1>&2 || true
        echo NOOP sudo apt-file update                          1>&2 || true
        echo FOOOOOOOO
        echo NOOP apt-cache search ruby | grep '^ruby' | sort || true
        sudo apt-get --assume-yes install -V debian-goodies || true
        sudo apt-get --assume-yes install -V gdb            || true
        echo NOOP sudo apt-get --assume-yes --allow-downgrades install -V ruby2.5=2.5.1-1ubuntu1 libruby2.5=2.5.1-1ubuntu1 || true
        sudo apt-get --assume-yes --allow-downgrades install -V ruby2.5=2.5.1-1ubuntu1 libruby2.5=2.5.1-1ubuntu1 ruby2.5-dbgsym=2.5.1-1ubuntu1 libruby2.5-dbgsym=2.5.1-1ubuntu1 libgmp10-dbgsym || true
        sudo apt-get --assume-yes install -V ruby2.6        || true
        echo FOOOOOOOOO
        apt-cache policy ruby2.5           1>&2 || true
        apt-cache policy ruby2.5-dbgsym    1>&2 || true
        apt-cache policy libruby2.5        1>&2 || true
        apt-cache policy libruby2.5-dbgsym 1>&2 || true
        echo NOOP sudo apt-get --assume-yes --allow-downgrades install -V libgmp10-dbgsym libruby2.5-dbgsym=2.5.1-1ubuntu1 ruby2.5-dbgsym=2.5.1-1ubuntu1 || true
        echo FOOOOOOOOOO
        find-dbgsym-packages /usr/bin/ruby2.6 || true
        echo FOOOOOOOOOOO
        find-dbgsym-packages /usr/bin/ruby2.5 || true
        ( mkdir aljunk-src \
          && cd aljunk-src \
          && apt-get source libc6=2.27-3ubuntu1     \
          && apt-get source libgmp10=2:6.1.2+dfsg-2 \
          && apt-get source ruby2.5=2.5.1-1ubuntu1  \
          && ls -l                                  \
        ) || true
        apt-cache policy libc6      || true
        apt-cache policy libgmp10   || true
        apt-cache policy ruby2.5    || true
        set +x
        printf '%s\n' 'ALJUNK: B'   1>&2
        set -x
        ( set -x
          mkdir aljunk-gdb \
          && cd aljunk-gdb \
          && cat - <<'EOGDB' >> aljunk.gdb
        set trace-commands on
        set verbose on
        set width unlimited
        set pagination off
        set debug auto-load off
        set startup-with-shell off
        #set exec-wrapper /usr/bin/setsid
        set breakpoint pending on
        set listsize 40
        # file /bin/bash
        # set args -c 'env | sort; echo; echo aljunk: ${HOME}'
        file /usr/bin/ruby2.5
        set args -e 'Dir.home;'
        break main
        break rb_home_dir_of
        commands 1 2
            printf "\nvvvvvvvvvv ALJUNK-bt\n"
            backtrace
            printf "^^^^^^^^^^\n\n\n"
            continue
        end
        break dir_s_home
        commands
            printf "\nvvvvvvvvvv ALJUNK-bt\n"
            backtrace
            list dir_s_home
            continue
        end
        break ruby2.5-2.5.1/dir.c:3058
        commands
            list 3058
            printf "ALJUNK: show user arg\n"
            print user
            continue
        end
        break ruby2.5-2.5.1/dir.c:3066
        commands
            list 3066
            printf "ALJUNK: foothold? What is user?\n"
            print user
            continue
        end
        break rb_default_home_dir
        commands
            printf "\nvvvvvvvvvv ALJUNK-bt\n"
            backtrace
            info threads
            list rb_default_home_dir
            printf "ALJUNK: try set dir from getenv of HOME\n"
            continue
        end
        #break ruby2.5-2.5.5/file.c:3427
        #break ruby2.5-2.5.5/file.c:3420
        break ruby2.5-2.5.1/file.c:3420
        commands
            # list 3427
            list 3420
            printf "ALJUNK: show dir (should be 0x0)\n"
            print dir
            continue
        end
        break getlogin.c:34
        commands
            printf "\nvvvvvvvvvv ALJUNK-bt\n"
            backtrace
            list 34
            printf "ALJUNK: checking name (prior to setting; should be empty string here)\n"
            print name
            info breakpoints
            continue
        end
        break getlogin.c:35
        commands
            list 35
            printf "ALJUNK: what is res?\n"
            print res
            continue
        end
        break __getlogin_r_loginuid
        commands
            printf "\nvvvvvvvvvv ALJUNK-bt\n"
            backtrace
            info threads
            list __getlogin_r_loginuid
            continue
        end
        break getlogin_r.c:38
        commands
            list 38
            printf "ALJUNK: what is fd?\n"
            print fd
            continue
        end
        break getlogin_r.c:46
        commands
            set listsize 50
            list 46
            set listsize 40
            printf "ALJUNK: what is n?\n"
            print n
            continue
        end
        break getlogin_r.c:65
        commands
            set listsize 50
            list 65
            set listsize 40
            printf "ALJUNK: what is uid?\n"
            print uid
            printf "ALJUNK: what is uidbuf?\n"
            print uidbuf
            continue
        end
        break getlogin_r.c:81
        commands
            set listsize 50
            list 81
            set listsize 40
            printf "ALJUNK: what is res?\n"
            print res
            printf "ALJUNK: what is tpwd?\n"
            print tpwd
            printf "ALJUNK: what is pwd?\n"
            print pwd
            printf "ALJUNK: what is buf?\n"
            print buf
            printf "ALJUNK: what is buflen?\n"
            print buflen
            continue
        end
        break getlogin_r.c:88
        commands
            set listsize 50
            list 88
            set listsize 40
            printf "ALJUNK: what is needed?\n"
            print needed
            printf "ALJUNK: what is namesize?\n"
            print namesize
            continue
        end
        break __getpwuid_r
        commands
            set listsize 500
            list __getpwuid_r
            set listsize 40
            printf "ALJUNK: what is INTERNAL"
            macro expand INTERNAL
            printf "ALJUNK: what is REENTRANT_NAME"
            macro expand REENTRANT_NAME
            printf "ALJUNK: what is ADD_PARAMS"
            macro expand ADD_PARAMS
            printf "ALJUNK: what is LOOKUP_TYPE"
            macro expand LOOKUP_TYPE
            printf "ALJUNK: what is H_ERRNO_PARM"
            macro expand H_ERRNO_PARM
            printf "ALJUNK: what is EXTRA_PARAMS"
            macro expand EXTRA_PARAMS
            continue
        end
        #
        # AL.NOTE: this is the macro that expands into __getpwuid_r
        #break nss/getXXbyYY_r.c:191
        break getXXbyYY_r.c:206
        commands
            set listsize 500
            list 206
            set listsize 40
            continue
        end
        break ruby2.5-2.5.1/file.c:3421
        commands
            # list 3429
            list 3421
            printf "ALJUNK: ABOUT to try to set login from getlogin. Goes different here.\n"
            continue
        end
        #break ruby2.5-2.5.5/file.c:3429
        #break ruby2.5-2.5.5/file.c:3422
        break ruby2.5-2.5.1/file.c:3422
        commands
            # list 3429
            list 3422
            printf "ALJUNK: tried to set login from getlogin (may or may not be 0x0)\n"
            print login
            printf "ALJUNK: in rb_default_home_dir; continuing\n"
            continue
        end
        info breakpoints
        directory /home/runner/work/netrc-rb/netrc-rb/aljunk-src/glibc-2.27
        directory /home/runner/work/netrc-rb/netrc-rb/aljunk-src/glibc-2.27/locale
        directory /home/runner/work/netrc-rb/netrc-rb/aljunk-src/glibc-2.27/login
        directory /home/runner/work/netrc-rb/netrc-rb/aljunk-src/glibc-2.27/stdlib
        directory /home/runner/work/netrc-rb/netrc-rb/aljunk-src/glibc-2.27/sysdeps
        directory /home/runner/work/netrc-rb/netrc-rb/aljunk-src/gmp-6.1.2+dfsg
        directory /home/runner/work/netrc-rb/netrc-rb/aljunk-src/ruby2.5-2.5.1
        directory /home/runner/work/netrc-rb/netrc-rb/aljunk-src/ruby2.5-2.5.1/include
        unset environment HOME
        run
        printf "ALJUNK here\n"
        backtrace
        c
        q
        EOGDB
          : ALJUNK: SHOW CONTENTS OF GDB COMMANDS SCRIPT
          cat aljunk.gdb 1>&2 || true
          cat - <<'EODRIVER' > algo-gdb
        #!/bin/bash -
        declare -r PROG='algo-gdb'
        set -x
        gdb -q < './aljunk.gdb' | tee './aljunk-gdb.log'
        EODRIVER
          : ALJUNK: SHOW CONTENTS OF GDB DRIVER SCRIPT
          cat ./algo-gdb 1>&2 || true
          chmod 0755 ./algo-gdb \
          && ./algo-gdb         \
        ) || true
        : ALJUNK: SHOW CONTENTS OF ALJUNK-GDB.LOG file
        cat aljunk-gdb/aljunk-gdb.log 1>&2 || true
        set +x
        printf '%s\n' 'ALJUNK: b'   1>&2
        echo home ech: $HOME        1>&2
        echo home exp: ~            1>&2
        printf '%s\n' 'ALJUNK: C'   1>&2
        getent passwd runner        1>&2
        printf '%s\n' 'ALJUNK: D'   1>&2
        getent passwd               1>&2
        printf '%s\n' 'ALJUNK: E'   1>&2
        set                         1>&2
        printf '%s\n' 'ALJUNK: F'   1>&2
        ruby -e 'print "ruby dir home: #{Dir.home}\n";' 1>&2
        ruby -e 'print "ruby dir pwd:  #{Dir.pwd}\n";'  1>&2
        ruby -e 'print Dir.respond_to?(:home)   ? "yep1\n" : "nope1\n";' 1>&2
        ruby -e 'print File.readable?(Dir.home) ? "yep2\n" : "nope2\n";' 1>&2
        printf '%s\n' 'ALJUNK: G'   1>&2
        set -x
        cat - <<EOS > scmd
        #!/bin/bash -
        printf 'start of scmd\n' 1>&2
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec --keep-file-descriptors ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)' 
        EOS
        chmod 0755 scmd
        script -e -f -c './scmd' output.aljunk || printf 'AL.DEBUG: estat of scmd: %s\n' "$?" 1>&2 && true || true
        printf 'after: start of scmd output:\n' 1>&2
        echo NOOP cat output.aljunk                       1>&2
        printf 'after: end of scmd output:\n'   1>&2
        set +x
        printf '%s\n' 'ALJUNK: H'   1>&2
        set -x
        printf '%s\n' 'aljunk: 10'  1>&2
        /usr/bin/ruby2.5 -e 'print "foo: #{Dir.respond_to?(:home) && File.readable?(Dir.home) ? Dir.home : Dir.pwd}\n";'  || true
        printf '%s\n' 'aljunk: 20'  1>&2
        /usr/bin/ruby2.5 -e 'print "foo: #{Dir.respond_to?(:home) && File.readable?(Dir.home) ? Dir.home : Dir.pwd}\n";' 1>&2  || true
        printf '%s\n' 'aljunk: 30'  1>&2
        ( /usr/bin/ruby2.5 -e 'print "foo: #{Dir.respond_to?(:home) && File.readable?(Dir.home) ? Dir.home : Dir.pwd}\n";' )   || true
        #
        # AL.DEBUG working here: this is the first one to break
        printf '%s\n' 'aljunk: 40'  1>&2
        ( unset HOME; /usr/bin/ruby2.5 -e 'print "foo: #{Dir.respond_to?(:home) && File.readable?(Dir.home) ? Dir.home : Dir.pwd}\n";' )  || true
        #
        #
        printf '%s\n' 'aljunk: 42'  1>&2
        ( unset HOME; /usr/bin/ruby2.5 -e 'print "foo: #{Dir.respond_to?(:home)}\n";' )  || true
        #
        printf '%s\n' 'aljunk: 44'  1>&2
        ( unset HOME; /usr/bin/ruby2.5 -e 'print "foo: #{Dir.home}\n";' )  || true
        #
        printf '%s\n' 'aljunk: 45'  1>&2
        ( unset HOME; /usr/bin/ruby2.5 -e 'Dir.home'; estat=$?; echo estat $estat; exit $estat )  || true
        #
        printf '%s\n' 'aljunk: 46'  1>&2
        ( unset HOME; /usr/bin/ruby2.5 -e 'print "foo: #{File.readable?(Dir.home)}\n";' )  || true
        #
        printf '%s\n' 'aljunk: 48'  1>&2
        ( unset HOME; /usr/bin/ruby2.5 -e 'print "foo: #{Dir.pwd}\n";' )  || true
        #
        #
        printf '%s\n' 'aljunk: 50'  1>&2
        ( unset HOME; /usr/bin/ruby2.5 -e 'print "foo: #{Dir.respond_to?(:home) && File.readable?(Dir.home) ? Dir.home : Dir.pwd}\n";' ) 1>&2  || true
        printf '%s\n' 'aljunk: 60'  1>&2
        true | ( unset HOME; /usr/bin/ruby2.5 -e 'print "foo: #{Dir.respond_to?(:home) && File.readable?(Dir.home) ? Dir.home : Dir.pwd}\n";' ) 1>&2  || true
        printf '%s\n' 'aljunk: 70'  1>&2
        true | ( unset HOME; /usr/bin/ruby2.5 -e 'print "foo: #{Dir.respond_to?(:home) && File.readable?(Dir.home) ? Dir.home : Dir.pwd}\n";' ) 1>&2 | cat  || true
        printf '%s\n' 'aljunk: 80'  1>&2
        true | ( unset HOME; setsid /usr/bin/ruby2.5 -e 'print "foo: #{Dir.respond_to?(:home) && File.readable?(Dir.home) ? Dir.home : Dir.pwd}\n";' ) 1>&2 | cat  || true
        printf '%s\n' 'aljunk: 90'  1>&2
        set +x
        printf '%s\n' 'ALJUNK: I'   1>&2
        printf '%s\n' 'ALJUNK: end' 1>&2
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec --keep-file-descriptors ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
        printf '%s\n' 'ALJUNK: I'   1>&2
        bundle exec --keep-file-descriptors /usr/bin/ruby2.5 -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
