name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        echo NOOP set -e
        printf '%s\n' 'ALJUNK: go' 1>&2
        /usr/bin/env 1>&2
        printf '%s\n' 'ALJUNK: A'   1>&2
        echo home decl is ${HOME@A} 1>&2
        printf '%s\n' 'ALJUNK: a'   1>&2
        echo $(pwd)                 1>&2
        printf '%s\n' 'ALJUNK: b'   1>&2
        ls -la                      1>&2
        printf '%s\n' 'ALJUNK: c'   1>&2
        echo maybe tty: $(tty)      1>&2
        printf '%s\n' 'ALJUNK: d'   1>&2
        set -x
        grep intel_pt /proc/cpuinfo || true
        echo FOO
        sudo apt-get --assume-yes install debian-goodies gdb
        echo FOOO
        find-dbgsym-packages /usr/bin/ruby2.6 || true
        set +x
        printf '%s\n' 'ALJUNK: B'   1>&2
        echo home ech: $HOME        1>&2
        echo home exp: ~            1>&2
        printf '%s\n' 'ALJUNK: C'   1>&2
        getent passwd runner        1>&2
        printf '%s\n' 'ALJUNK: D'   1>&2
        getent passwd               1>&2
        printf '%s\n' 'ALJUNK: E'   1>&2
        set                         1>&2
        printf '%s\n' 'ALJUNK: F'   1>&2
        ruby -e 'print "ruby dir home: #{Dir.home}\n";' 1>&2
        ruby -e 'print "ruby dir pwd:  #{Dir.pwd}\n";'  1>&2
        ruby -e 'print Dir.respond_to?(:home)   ? "yep1\n" : "nope1\n";' 1>&2
        ruby -e 'print File.readable?(Dir.home) ? "yep2\n" : "nope2\n";' 1>&2
        printf '%s\n' 'ALJUNK: G'   1>&2
        set -x
        cat - <<EOS > scmd
        #!/bin/bash -
        printf 'start of scmd\n' 1>&2
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)' 
        EOS
        chmod 0755 scmd
        script -e -f -c './scmd' output.aljunk
        printf 'AL.DEBUG: estat of scmd: %s\n' "$?" 1>&2
        printf 'after: start of scmd output:\n' 1>&2
        cat output.aljunk                       1>&2
        printf 'after: end of scmd output:\n'   1>&2
        set +x
        printf '%s\n' 'ALJUNK: H'   1>&2
        printf '%s\n' 'ALJUNK: end' 1>&2
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
