name: Whatever

on:
    push:
        branches: [ ads/filehome-vs-login-muckage ]

    pull_request:
        branches: [ ads/filehome-vs-login-muckage ]

jobs:
    mybuild:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Run my debugging commands
              run: |
                echo NOOP set -e
                printf '%s\n' 'ALJUNK: go' 1>&2
                set -x
                /usr/bin/whoami             1>&2 || true
                /usr/bin/id                 1>&2 || true
                /usr/bin/id --user          1>&2 || true
                /usr/bin/getent passwd $(/usr/bin/id --user) 1>&2 || true
                echo                        1>&2 || true
                /usr/bin/ruby2.5 -e 'print "process uid: #{Process.uid}\n";' 1>&2 || true
                /usr/bin/ruby2.5 -r etc -e 'print "can we load the etc module? Record: #{Etc.getpwuid( Process.uid )}\n";' 1>&2 || true
                echo                             1>&2 || true
                /usr/bin/ruby2.5 -e 'Dir.home;'  1>&2 || true
                echo $?                          1>&2 || true
                ( set -x; unset HOME; /usr/bin/ruby2.5 -e 'Dir.home;'; echo $? ) 1>&2 || true
