name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        printf '%s\n' 'ALJUNK: go' 1>&2
        /usr/bin/env 1>&2
        printf '%s\n' 'ALJUNK: A'   1>&2
        echo home decl is ${HOME@A} 1>&2
        printf '%s\n' 'ALJUNK: B'   1>&2
        set 1>&2
        printf '%s\n' 'ALJUNK: end' 1>&2
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
