name: Ruby

on:
  push:
    branches: [ ads/filehome-vs-login-muckage ]
  pull_request:
    branches: [ ads/filehome-vs-login-muckage ]

# foo: bogon comment; will this trigger the action even though this branch is not listed above?
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
